### PR TITLE
update to new fody packaging

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by nuitsjp** [comment]
Oh! Thank you for a wonderful PR.
However, it seems that my understanding of Fody is not enough.
Look closely at PR and then consider merge.
Anyway, thanks for the wonderful work.

**Comment by nuitsjp** [comment]
I was able to confirm.
Thank you for the great PR.
I cannot express enough my feelings of appreciation.

**Comment by SimonCropp** [comment]
note there are also some test helper to help u verify your code eg https://github.com/Fody/Caseless/blob/master/Tests/ModuleWeaverTests.cs#L15

**Comment by nuitsjp** [comment]
Thank you. I will study.

**Pull request merged**
